### ISSUE TITLE
envoy returns "no healthy upstream"

### ISSUE THREAD

**Issue by em230418** [xoe-labs/dockery-odoo-scaffold#28]
To reproduce:
```
odooup init test
cd test
make create
make build # again. Makefile does not run build twice
docker-compose run odoo
```

But odoo is accessible. You need to get ip address via `docker inspect` and enter it with port 8069.

**Comment by blaggacao** [comment]
http://odoo.localhost ?

**Comment by em230418** [comment]
```
$ curl -v http://odoo.localhost/
*   Trying ::1...
* Connected to odoo.localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: odoo.localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Wed, 10 Jul 2019 05:24:43 GMT
< server: envoy
< 
* Connection #0 to host odoo.localhost left intact
no healthy upstream
```

**Comment by blaggacao** [comment]
@em230418 PWhen you do docker-compose up do you see such line:
`ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint test_proxy_1 (d703fe975c991633a74b265792f42e291d962eb8f48413c641f9c06f91a7bfa2): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.` ?

**Comment by blaggacao** [comment]
You could identify the project and do: `docker-compose -p <project> down`

**Comment by blaggacao** [comment]
@em230418 I can confirm that it does not reproduce on my end. Everything works as expected.

**Comment by blaggacao** [comment]
@em230418 Still, please ping me here, if you need help wih further debugging....

**Comment by em230418** [comment]
My mistake was launching odoo via
```
docker-compose run odoo
```
when I had to
```
docker-compose up odoo
```
Sorry for my inattention

**Comment by blaggacao** [comment]
OK, and sorry I also overlooked.
