### ISSUE TITLE
debug=assest doesn't work

### ISSUE THREAD

**Issue by yelizariev** [xoe-labs/dockery-odoo-scaffold#33]
I get 503 error (_upstream connect error or disconnect/reset before headers. reset reason: connection termination_) on random static files during the openning odoo backend in debug=assets mode.

It happen only in [pale moon browser](http://linux.palemoon.org/), that we use for remote development

**Comment by yelizariev** [comment]
I report it here, because debug=assets work in runbot

**Comment by yelizariev** [comment]
Ok, the same happens in firefox (remote firefox and local)

**Comment by yelizariev** [comment]
Chrome too. So, not a browser issue

**Comment by yelizariev** [comment]
I tried to increase ``connect_timeout`` in envoy to 100sec, but it doesn't help

**Comment by em230418** [comment]
> I get 503 error (upstream connect error or disconnect/reset before headers. reset reason: connection termination) on random static files during the openning odoo backend in debug=assets mode.

+1

**Comment by blaggacao** [comment]
@agentdeu Didn't we already solve this issue in the last iteration?

I'll debug again with latest version...

**Comment by yelizariev** [comment]
Do you mean this update: https://github.com/xoe-labs/dockery-odoo-scaffold/commit/78a2c15ff2d5a99fb85e06a52bce48893997fb8c#diff-644407ce240322229b0cad20bbc444a2 ? I haven't tried it, actually.

**Comment by blaggacao** [comment]
Yes

**Comment by blaggacao** [comment]
Is this working as expected with the above update?

**Comment by yelizariev** [comment]
@em230418 could you check please?

**Comment by em230418** [comment]
> Do you mean this update: [78a2c15#diff-644407ce240322229b0cad20bbc444a2](https://github.com/xoe-labs/dockery-odoo-scaffold/commit/78a2c15ff2d5a99fb85e06a52bce48893997fb8c#diff-644407ce240322229b0cad20bbc444a2) ? I haven't tried it, actually.

I confirm, that with this commit everything is ok. No 503 responses.
